framework_packages:
- name: _framework-pkg
  package_type: external
  exportable: true
  repo: de3-framework-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-framework-pkg-repo.git
  git_ref: main
- name: aws-pkg
  package_type: external
  exportable: true
  repo: de3-aws-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-aws-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: azure-pkg
  package_type: external
  exportable: true
  repo: de3-azure-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-azure-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: de3-gui-pkg
  package_type: external
  exportable: true
  repo: de3-gui-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-gui-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: gcp-pkg
  package_type: external
  exportable: true
  repo: de3-gcp-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-gcp-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: image-maker-pkg
  package_type: external
  exportable: true
  repo: de3-image-maker-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-image-maker-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: maas-pkg
  package_type: external
  exportable: true
  repo: de3-maas-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-maas-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: mesh-central-pkg
  package_type: external
  exportable: true
  repo: de3-mesh-central-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-mesh-central-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: mikrotik-pkg
  package_type: external
  exportable: true
  repo: de3-mikrotik-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-mikrotik-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: proxmox-pkg
  package_type: external
  exportable: true
  repo: de3-proxmox-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-proxmox-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: unifi-pkg
  package_type: external
  exportable: true
  repo: de3-unifi-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-unifi-pkg-repo.git
  git_ref: main
  config_source: pwy-home-lab-pkg
- name: pwy-home-lab-pkg
  package_type: embedded
  exportable: false
  is_main_package: true
