pwy-home-lab-pkg_secrets:
  config_params:
    pwy-home-lab-pkg/_stack/maas/pwy-homelab:
      _provider_maas_api_key: ENC[AES256_GCM,data:jwIrJGBXGS2QsOHxaSeefM4VR+J/voz0dmvj57NcsWav1aHVE2nP2Oae085tFKHKtNFVFE/aOYn6Q2LFdNsfYIGWcOlkog==,iv:8hKKI2wUciCgn5jy1YqsMjo8yIlLhxQOgTxdwdRq7z8=,tag:Qpw7IH3ggXMHDwQZiyx6Ig==,type:str]
    pwy-home-lab-pkg/_stack/maas/pwy-homelab/machines/ms01-01:
      power_pass: ENC[AES256_GCM,data:OXrRlMyZljJv8VQo6gcHBA==,iv:plsW6aVjBq12uutsCO4r6aOTkebds8gE2kRl5I6isbI=,tag:zC1OQT4U0UeQkdC8Xt/hcw==,type:str]
      power_user: ENC[AES256_GCM,data:eMfOTZI=,iv:aAHuGB0XVjWsKGIVYW5bYC0+lvztHgdKUd/JQaAMUrE=,tag:tjtwxnhX4IkTmFoM59eSeA==,type:str]
      smart_plug_password: ENC[AES256_GCM,data:wzCjG71hVyZ01w==,iv:uYo5qe0OBSZiJHBunx/yLYV7uiL8EkNwXGS3slrAXP0=,tag:+dkPtWC/XagTJsIjj8of/Q==,type:str]
      smart_plug_username: ENC[AES256_GCM,data:OjFLO6EP7fJxy4nE1SQVQlM+gHQGAQ==,iv:04bGAQBF2ui2m7gOQLcIbg8KDoLy/rEx98eGDSYYwdU=,tag:C7jl0Nr59YkMKu71kXViYQ==,type:str]
    pwy-home-lab-pkg/_stack/maas/pwy-homelab/machines/ms01-02:
      #ENC[AES256_GCM,data:M2r18yGSKHPVkW6B+xHFhJpGBQus0/IB5jUX6HU3d4hRY4P6Hrf4hEdoTqfksh9o,iv:teScvGX9VbNcyuFnS0g4APqjxXJ9oCht2eeY4wBCD6Y=,tag:JtqkyF0nJ6TPzT5vWuaq/g==,type:comment]
      power_pass: ENC[AES256_GCM,data:6fNEcoKrpEw75wscIrg=,iv:CBo9ETzd2DGjpYCTF6lVInoq/VwP/VAwRuoxd6Vc1UY=,tag:RJvLrz5Gr9f24++qSvQ8vw==,type:str]
      power_user: ENC[AES256_GCM,data:blGRgsU=,iv:Crjp5SzbaxHkJ1g+CvsP6ZJEzTB843XCF7G9kP/XSjc=,tag:9YD79DPLVndmN2DINFBnDg==,type:str]
      smart_plug_password: ENC[AES256_GCM,data:v9Rai7fPDeHzXQ==,iv:XxW6SKWVRqw8CYc4S1fuFXAV2+pVE6G+1W1A07DHK/M=,tag:kOQEIzHQ61AyZJgJ/cWJcA==,type:str]
      smart_plug_username: ENC[AES256_GCM,data:GxQ1yGk+5MaaSzBWyjlxZZwZCuCZpA==,iv:tl2phQxfRZuGTAicCfnn+ugw2v7aZm9nbtH/wV1c1I8=,tag:W/zdVNX7dBrhSGF/A2lAog==,type:str]
    pwy-home-lab-pkg/_stack/maas/pwy-homelab/machines/ms01-03:
      power_pass: ENC[AES256_GCM,data:ebC+NytD+CV9AkchonoAQw==,iv:GdXd/GoOrp0fNTn1KjpO8pn38s0IBpO0P24NFhzIMOE=,tag:JKAGla6FFljaaxphQ2zmLA==,type:str]
      power_user: ENC[AES256_GCM,data:YqINnvY=,iv:rZV+7EzlB03UqSKtzhDPld7m8p5akJAI4QKrQJSsIoA=,tag:1/ulc71dAWrLOBFn3H9yeA==,type:str]
      smart_plug_password: ENC[AES256_GCM,data:5t7fJyfZyORdcA==,iv:BcpxGZDxENmS4gXmTm3Ldo28uDqEVRYUxfAFk3+Z4iE=,tag:WjqA/JpKBgTCET4IfaNalg==,type:str]
      smart_plug_username: ENC[AES256_GCM,data:MrRYEtesUZoJcCgkH15BMB1b8YU/rQ==,iv:bN4wTlJh4rRQK2hsZs4SfbBF5jxD1vdfahMw0RxBktc=,tag:y248N3rowatHezrKB5nuKA==,type:str]
    pwy-home-lab-pkg/_stack/maas/pwy-homelab/machines/nuc-1:
      smart_plug_password: ENC[AES256_GCM,data:HClO2OHqPiwTS5F4X/qV,iv:Mx/A3VsCxWnU6oR0hfZkjnudjLrF4O8YixkKyk9kKl8=,tag:FMbAGAOQwZptkgBb4G/Tgw==,type:str]
      smart_plug_username: ENC[AES256_GCM,data:q2jFY0OuswoETzpBRo9U,iv:bAZLx/BFq1zf2LJx5Jp1DG5pzPpdhUq2d9Pd6fb60ww=,tag:z5MffAALlxBQWf1pjgPc8w==,type:str]
    pwy-home-lab-pkg/_stack/maas/pwy-homelab/machines/pxe-test-vm-1:
      power_pass: ""
      power_token_name: ENC[AES256_GCM,data:gJABWUpHu8VcZW8=,iv:SoxoWW4I0kNyIRePs7ZKg2ApHIRqlGoJMl2+e9fj9z4=,tag:Y7xhW210Hxbw4FXdaB9M8Q==,type:str]
      power_token_secret: ENC[AES256_GCM,data:bWLKWIe/pu10RuasPFz8FmQ9LbPsNOmtjI9Pw5uCeWsQ1s1J,iv:z0q/PQFvIeTuaxUG11bHJqcW/inuUKcZ/kf1x3i+Fq8=,tag:UeOdfaBQHI1e+xCAsS29aA==,type:str]
      power_user: ENC[AES256_GCM,data:1VxB8yJdZoc=,iv:nIBJET+XwHXAZc9zmvAU3eOL4hdfZvmdIZnnsgDCuo8=,tag:Q4Jbe7S9sTQ6alGR5U71ww==,type:str]
    pwy-home-lab-pkg/_stack/null/pwy-homelab/maas/configure-server:
      admin_password: ENC[AES256_GCM,data:Y65oIEQYsnma2A==,iv:VzwfyZ0LJHfEKwsKDaE20IvPnJmByzfv3XylWZYt/2E=,tag:ekIGlX93MDDBZAkUzvOYeg==,type:str]
      db_password: ENC[AES256_GCM,data:N0gvoskBX/nri+i+ELs=,iv:pfCAT8wLlfE11ZhQrqfpwm4n7wrauGw4VFnrag13l0w=,tag:t6vAGjZ9KjNxssn953Lr1Q==,type:str]
      machine_deploy_password: ENC[AES256_GCM,data:Wvl6e+SwsNCjGMnOyg==,iv:Fgg79HvZ0Fi6sldbN1uSNsDfrTc5uoZiQlWTZbcvddo=,tag:lPAbOUrsQkuLNkDrQQodZg==,type:str]
      proxmox_power:
        api_token_secret: ENC[AES256_GCM,data:BpHyrrh8P2Cw85i4bkKxp0rXq5NyyBZuVv3Hqtp1GmbYGCQw,iv:HzxlD9AqWfNv7P1yhr61OryR95UbZJz1dh/MmaOgXPc=,tag:Rmf0f+dvrpDzhKjccv6keA==,type:str]
        api_user: ENC[AES256_GCM,data:y5ktScws2ND15Ew4wK7U6DbOLsg=,iv:vklJMw7IIepdcPjbJaD2YyQ9VHu/kIdo97PRWRps2Vk=,tag:/nPo9FAfW0rACGWrAgbiVg==,type:str]
    pwy-home-lab-pkg/_stack/proxmox/pwy-homelab/pve-nodes/ms01-01:
      _provider_proxmox_token_id: ENC[AES256_GCM,data:0kDx9u7LLl0DqTP60LQhPKA=,iv:s+am30o6U3g1LYOWYLL4hlcsl0qS5yM9dIm4A0HKxTs=,tag:r2C682grvrDU+wJZywAWSQ==,type:str]
      _provider_proxmox_token_secret: ENC[AES256_GCM,data:/VHYqPJ0eULJsSx8lO+r14Hzr1nBvSg7CITl5d8Bb3ErRaL0,iv:p1xGFWOrgL6cWmM6HFgzuo11fF0bETPHxR/nKG9KYDA=,tag:SODiCQoOPS35n387D3pVJg==,type:str]
    pwy-home-lab-pkg/_stack/proxmox/pwy-homelab/pve-nodes/pve-1:
      _provider_proxmox_password: ENC[AES256_GCM,data:CL5M7dqy9Ip49w==,iv:PlVXj2meUuWfe/GpYgFzq1mjuumhKF/7IG2o+hogrR4=,tag:xlsPPDZWixkbSDXfMKjqAQ==,type:str]
      _provider_proxmox_token_id: ENC[AES256_GCM,data:+qVUu/lS/iJNPJVf3NW3jvk=,iv:JHSiQgDA56DMwHiT1SYpq4Yh8cO18K/cvqi8yks8Y8E=,tag:cqWt7UTONec7a5t8aO6C3A==,type:str]
      _provider_proxmox_token_secret: ENC[AES256_GCM,data:czV8zPFfuO6OC8VfK522CvvsEoTlzwO17Ble4pVhKwsOm3x/,iv:9Wrzi97fkgfEfXkhM9qAARy39MZweoo13yHY5T7QcXE=,tag:tPswn8KcPZKpJie9X5sZtw==,type:str]
      _provider_proxmox_username: ENC[AES256_GCM,data:Rtad1w==,iv:geIeAgF3EOaslpKX4+NHlcz7nlngB26La4jTpYgNS/w=,tag:LIvshc6kopdqFXbw6+xTlw==,type:str]
      cloud_init_password: ENC[AES256_GCM,data:2p+Mcppe710ok3Ttv0Dn7A==,iv:sZUp/MJY4WvKTxGqkdRBg4gGIkvfsquSk3UihRg85GM=,tag:/X8Uf35m31e+evKVQNbS0Q==,type:str]
      nodeName: ENC[AES256_GCM,data:gRcv,iv:9R/FgnLBxHJs7EXoDWoqRtUV65x0ELhCJhs/1hcd6VA=,tag:Yo9QjV7aRPZsPonU+QbIDg==,type:str]
    pwy-home-lab-pkg/_stack/proxmox/pwy-homelab/pve-nodes/pve-2:
      _provider_proxmox_password: ENC[AES256_GCM,data:icULmXW9+CaGqA==,iv:zJ/bQKisXfEcdWxGnC88g7JhujHLCSQJbWlB+I9flO0=,tag:nLxWJFGYp/lD6FEJO8d3Ew==,type:str]
      _provider_proxmox_token_id: ENC[AES256_GCM,data:j/t/7f0D6RH28agW/LKfb7U=,iv:USaaWCpgTHXN0VKOZQ08/9qKla6MbVrTR6tQePoDd0g=,tag:9rqH9eYzLChFhOPrGcKkRQ==,type:str]
      _provider_proxmox_token_secret: ENC[AES256_GCM,data:dbmEpPChyfIIK8pOtUQWqjaO7AT2ufGKjzmuMTWMMbZ9Sd8k,iv:QWr1BnoPMjZbK62OpPRHA6QS0lPjs6iD8xTplNQT+p8=,tag:WsGsqBw67drlV1IK+TWqDw==,type:str]
      _provider_proxmox_username: ENC[AES256_GCM,data:i+f0kw==,iv:BYd8mVN48XmO0FiaRqL+8z/aPyH6OkVvDp2P7meMzhc=,tag:uP0zGLTXjmv/0DbFpuHqiw==,type:str]
      cloud_init_password: ENC[AES256_GCM,data:C9r/AIM3X8UqWfjhenKcKw==,iv:ZwtTOdr1Bv0WrbsCDGAIBZjJpAlPNioZ4+t7DIs1xHU=,tag:kyNlUhteptUY+VHDQwfDJg==,type:str]
      nodeName: ENC[AES256_GCM,data:4Rwcp1s=,iv:eE677K0mH08uTwxuJj7M5TksG9/uX6a68Dsm+8NM2Xo=,tag:txVCoc4ynv3hRsLgn16ELA==,type:str]
    pwy-home-lab-pkg/_stack/unifi/pwy-homelab:
      _provider_unifi_password: ENC[AES256_GCM,data:mRizAKobwCRx0g3hu4KQTJ8=,iv:Isy6EFDOOX0yYh9qEX6K5s5kPQ+saWOvYSYpqqDuDt0=,tag:xExk1ZKaQj+O3f+BNxTqvQ==,type:str]
      _provider_unifi_username: ENC[AES256_GCM,data:Hx/TOUkmR0iS,iv:Je9m5B+ylNxh4d0XPvSCJ+4k2HX/+HEt6vH82PpqxV0=,tag:rUfqewm6yYT/3/yktLHjOw==,type:str]
    pwy-home-lab-pkg/_stack/null/pwy-homelab/maas/configure-region:
      admin_password: ENC[AES256_GCM,data:Kk6VH1U0KkhZCw==,iv:iemOex6EWyXeUrsKNelCc3X00WwU6jtHaEgUsc9qOpA=,tag:9uTiF74gdMkGMGDbCXsZfg==,type:str]
      db_password: ENC[AES256_GCM,data:leJB3ifxe5ifG8ZvBdw=,iv:w/4zNuqUOTFRahEFd4xll9hPCHy+8Gn0BNniMkCKQio=,tag:TlMg0Po1VMeXjxbYD1JU3A==,type:str]
      machine_deploy_password: ENC[AES256_GCM,data:T4l6gyINAHVksfYobQ==,iv:yMnYXE4iPmHBgjuOJjX0ZjGSg6GCArY3qzPljG67eEA=,tag:r93ij4QBG4peFqPGzVs05A==,type:str]
      proxmox_power: ENC[AES256_GCM,data:VS9S4IUGAGotG12Hy6PeHXAPOxo+l6Q4+SgUQo2wMMCWxuTJ2Lg/wWF936jgsN5ZDaElTR0p/wa5zhG+0dnJSIRhwkwYOQbWhCALrEzIKHb7c9GTOeYliYWNlSaPV0U+,iv:/SNq4+VEHk6SVyahIqVZ0q40JSKrOm4neJaHIU6MyZ4=,tag:2FbaI/D06/ndkLLJo0JuDQ==,type:str]
    pwy-home-lab-pkg/_stack/routeros/pwy-homelab:
      _provider_routeros_username: ENC[AES256_GCM,data:cbeg1Gc=,iv:BUATSk/y0nilJ3Q/ynGA63mG2msaFRbdvFZM70+LLVI=,tag:a5Vy/rpLuI34Qz9ZTQinXQ==,type:str]
      _provider_routeros_password: ENC[AES256_GCM,data:fHgMXYhMQPz9TA==,iv:A7q5jiza8RkhZF3zH4ZEqtxIQ2/cMhFI1a4alGCsEIw=,tag:mWIO9s2hWUrE2c61cFy7UA==,type:str]
sops:
  lastmodified: "2026-04-18T17:13:24Z"
  mac: ENC[AES256_GCM,data:4jxxeGV1RMAPNLKgWv4XxlRAQqWEmdaMlTGBiQU7r4wiPtA3/H+7uePKQXcGcarS/DJDrOEm6fwq9f5LHqZRbKqUdHfVZYz07mA1PQkGjoiUIC3dDKwkmdGcYR33wbynxvmZAlhe7qKSwn+pjV0EN6yTdddtjcHHQxiVRIK4Tjg=,iv:o7fsmjsR/xLrbqPbIJ93e1qLoM3hLsUBHRMvy4pAVjE=,tag:nf2qJgCaqnD+NjliIx/lyg==,type:str]
  pgp:
    - created_at: "2026-04-13T14:29:35Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv9EvasEYAiQ7y2Pxw0jOezKqyZMI//LzNYg1pwYDcgFdor
        +67qerHvVZMn3YBbOvAAV30SJeknDDDo6phPczbDUEDusHN9zaqfTrDMbRZwX3rE
        4IdNskwwpr52IVmHfSQfL0ibg5tGs7Ct6D/GRTIah7MCizCCNqKt/rV/TLHQOzv7
        maaimAbWnOWae0Esz5TPCbwE+WVkwT+n95jyNYtYtj3r5RAkRF2XOjEkc9r+Pr8R
        HireOyD05djg4016e1zBmOsxBnBjiZq+xzU2rnRWUBvcGn66hXTJK5LvwtgqQhsw
        pzfoOCTYiRK3t9Q/2jQqe78hPJABSfDBVH3j37J0wI/DdtCclTCzXF3F7UNbds3R
        ifTcrESO+sYlQZNSzTWnjxsr7v2762AYl/yqWRq2nQLqgvIqvu09KeHZcgc5uW3e
        /00FzKv0BNeXfU/XKmTiwYwDHge3OgJgfNFmsFq/JgnV+/x0H80HplS7YiXeThrB
        NP8EdYnr1VAsOEiwaO8I0l4BKqQ8eitVV8yb7yuKbDPs/SH1SubmxhqCAj9ndyYh
        Y294p6pAemAg9gYnXWFv2tcJuIvJnajzhS/cTUrg7gCTSFV6IMT/cQjI439YO6Gq
        GQKDqjHnDCSpEwOC6eFE
        =Ypxr
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-04-13T14:29:35Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlARAA26OZYqwaEinCDc3SuAsQ12oRmRl76vpwA5ZnPzA8drfs
        9tmcNJxFnourYvaiykp29jypfFZFDklG71094XcmIj3N1L8uIfab7opBWz4DThL+
        DRKqjKPGdU5CyuUOBALLeeZhtLTzF0WHm5rFchSFjV2YL5ec7cotDKEztxpcaVk5
        SJhBjEuaZu/uZPZLjoWw+fFwzqPojtb0lP0i7s+xIQdoi4uVlF+oySgCZeakCNRP
        lz5uig8XU5CZrpAK+ZDDPP2+yUM9vCw+XRE0Dzng18N8WjxK3+D7zWXgLwz2QyRE
        l53ISHBuqqn8FkSk38JKimdl0lLgiuprUEQTbONcft1/YNz7jRBP2KEDaGyZkmzc
        OxHGXr1C2uueQRmzp3amZApLyS6QGdaQoqTILwX6SFuchFARsI52wmM7nxDsFjQc
        JN18Ja9LJIJy8OYQQLu95vPYsvqjsVj5QbZVqVRQ/ii2d4JhEWw0CDskKCOdyRhm
        gjxzC1if0yJ7AafiGSB8vpVtkvirYS2pKZjhVVB6fQfBpa5oiU5BcTUKg2br2Lwl
        Aru7oiw7ucqFX9ceMLcXsy+/+T7f7yOvV6AhNYynHvkBDgRKp8eDwvDe1YxzYeAl
        SZpesJ5h36cJY/ViVw1RBMb3y1y98chVDSff1ceaDVbPEXv+svesvaTXthJ0chHS
        XgE4jZAojZvlWM4sz3amxb3CpjhhGwoCLHi/rcQvUE+qEMKc92GV2YXUfuKTfFQx
        b0YOcPzeclCz9CKB0RCHtzw5SV53Wv1ZibZ8Vaqa4ISzyoiXZXFE68A5G2lidWU=
        =gWzU
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
